[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-run --list-chips`
runner = "probe-run --chip STM32F401RETx"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
